### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by John-Theo** [markslide/markslide#7]
Console warning appears after last pull.
Probably nothing...

> [Deprecation] /deep/ combinator is no longer supported in CSS dynamic profile.It is now effectively no-op, acting as if it were a descendant combinator. /deep/ combinator will be removed, and will be invalid at M65. You should remove it. See https://www.chromestatus.com/features/4964279606312960 for more details.

**Comment by awmleer** [comment]
fix in d3365d
