### ISSUE TITLE
Page size adapting

### ISSUE THREAD

**Issue by John-Theo** [markslide/markslide#8]
![image](https://user-images.githubusercontent.com/36699957/64079596-eb7a9080-cd1b-11e9-8bc6-11731734620a.png)

**Comment by John-Theo** [comment]
on-slide notificatipn bubble maybe a solution? like yuque comments. Let it overflow, and warn user to change markdown content.

**Comment by awmleer** [comment]
I think vertical overflowing is acceptable...

**Comment by John-Theo** [comment]
> I think vertical overflowing is acceptable...

Then what's its difference from [mubu](mubu.com)'s presentation mode??

**Comment by John-Theo** [comment]
@awmleer Pls close this issue if you have already resolved this problem.
